make enigma
./enigma --gear1 AEBCDFJGHIKOLMNPTQRSUYVWXZ --gear2 ACEDFHGIKJLNMOQPRTSUWVXZYB --gear3 ADCBEHFGILJKMPNOQTRSUXVWZY -sSEC -mICANDOTHAT

./enigma -d --gear1 AZXVTRPNDJHFLBYWUSQOMKIGEC --gear2 ABCDEFGHIJKLMNOPQRSTUVWXYZ --gear3 AZYXWVUTSRQPONMLKJIHGFEDCB -sAIN -mZJWNFNFNJ
